/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ffos.festival.view;

import ffos.festival.controller.ObradaFunkcija;
import ffos.festival.controller.ObradaIzvodjac;
import ffos.festival.model.Funkcija;
import ffos.festival.model.Izvodjac;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Endrina
 */
public class FormaIzvodjac extends javax.swing.JFrame {
    private ObradaIzvodjac oi;
    private ObradaFunkcija of;
    /**
     * Creates new form FormaIzvodjac
     */
    public FormaIzvodjac() {
        initComponents();
        oi = new ObradaIzvodjac();
        of = new ObradaFunkcija();

        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);

        DefaultComboBoxModel m = new DefaultComboBoxModel();
         for(Funkcija f : of.getFunkcijas()){
          m.addElement(f);
        }
            cmbFunkcija.setModel(m);
            ucitaj();
    }
    
    private void ucitaj() {
        DefaultListModel m = new DefaultListModel();
        for (Izvodjac i : oi.getIzvodjacs()) {
            m.addElement(i);
        }
        lstIzvodjac.setModel(m);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtImeIzvodjaca = new javax.swing.JTextField();
        txtPrezimeIzvodjaca = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cmbFunkcija = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstIzvodjac = new javax.swing.JList<>();
        btnDodaj = new javax.swing.JButton();
        btnObrisiizvodjac = new javax.swing.JButton();
        btnPromjeni = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Izvodjac");

        jLabel2.setText("Ime");

        jLabel3.setText("Prezime");

        txtImeIzvodjaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtImeIzvodjacaActionPerformed(evt);
            }
        });

        jLabel4.setText("Funkcija");

        cmbFunkcija.setToolTipText("");
        cmbFunkcija.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbFunkcijaActionPerformed(evt);
            }
        });

        lstIzvodjac.setToolTipText("");
        lstIzvodjac.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstIzvodjacValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstIzvodjac);

        btnDodaj.setText("Dodaj");
        btnDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajActionPerformed(evt);
            }
        });

        btnObrisiizvodjac.setText("obriši");
        btnObrisiizvodjac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiizvodjacActionPerformed(evt);
            }
        });

        btnPromjeni.setText("promjeni");
        btnPromjeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPromjeniActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtImeIzvodjaca)
                                    .addComponent(txtPrezimeIzvodjaca, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                                    .addComponent(cmbFunkcija, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(50, 50, 50))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(btnDodaj)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                                .addComponent(btnPromjeni)
                                .addGap(33, 33, 33)))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(btnObrisiizvodjac)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtImeIzvodjaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtPrezimeIzvodjaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(cmbFunkcija, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnDodaj)
                            .addComponent(btnPromjeni)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnObrisiizvodjac)
                .addGap(40, 40, 40))
        );

        cmbFunkcija.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajActionPerformed
        Izvodjac i = new Izvodjac();
        i.setIme(txtImeIzvodjaca.getText());
        i.setPrezime(txtPrezimeIzvodjaca.getText());
        i.setFunkcija((Funkcija)cmbFunkcija.getSelectedItem());
        oi.dodaj(i);
        ucitaj();
    }//GEN-LAST:event_btnDodajActionPerformed

    private void lstIzvodjacValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstIzvodjacValueChanged
         try {
            DefaultListModel m = (DefaultListModel)lstIzvodjac.getModel();
            Izvodjac i = (Izvodjac)m.get(lstIzvodjac.getSelectedIndex());
            txtImeIzvodjaca.setText(i.getIme());
            txtPrezimeIzvodjaca.setText(i.getPrezime());
        } catch (Exception e) {
        }
    }//GEN-LAST:event_lstIzvodjacValueChanged

    private void txtImeIzvodjacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtImeIzvodjacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtImeIzvodjacaActionPerformed

    private void btnPromjeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPromjeniActionPerformed
        Izvodjac i = null;
        try {
            DefaultListModel m = (DefaultListModel)lstIzvodjac.getModel();
            i = (Izvodjac)m.get(lstIzvodjac.getSelectedIndex());
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(rootPane, "Prvo odaberite stavku");
        }
        
        i.setIme(txtImeIzvodjaca.getText());
        i.setPrezime(txtPrezimeIzvodjaca.getText());
        i.setFunkcija((Funkcija)cmbFunkcija.getSelectedItem());
        oi.dodaj(i);
        ucitaj();
    }//GEN-LAST:event_btnPromjeniActionPerformed

    private void btnObrisiizvodjacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiizvodjacActionPerformed
        Izvodjac i = null;
        try {
            DefaultListModel m = (DefaultListModel)lstIzvodjac.getModel();
            i = (Izvodjac)m.get(lstIzvodjac.getSelectedIndex());
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(rootPane, "Prvo odaberite stavku");
        }
        
        i.setIme(txtImeIzvodjaca.getText());
        i.setPrezime(txtPrezimeIzvodjaca.getText());
        i.setFunkcija((Funkcija)cmbFunkcija.getSelectedItem());
        oi.obrisi(i);
        ucitaj();
    }//GEN-LAST:event_btnObrisiizvodjacActionPerformed

    private void cmbFunkcijaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbFunkcijaActionPerformed
        
    }//GEN-LAST:event_cmbFunkcijaActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodaj;
    private javax.swing.JButton btnObrisiizvodjac;
    private javax.swing.JButton btnPromjeni;
    private javax.swing.JComboBox<String> cmbFunkcija;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> lstIzvodjac;
    private javax.swing.JTextField txtImeIzvodjaca;
    private javax.swing.JTextField txtPrezimeIzvodjaca;
    // End of variables declaration//GEN-END:variables
}
